/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();

  // you can add a icon to a html canvas. simply supply its element id and the weather you want to show.
  skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  skycons.add("day1", Skycons.CLEAR_DAY);
  skycons.add("day2", Skycons.CLOUDY);
  skycons.add("day3", Skycons.RAIN);

  // start all icons animation!
  skycons.play();

  // update a icon on  canvas by its id
  skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);

var cities = ["Taipei City", "New Taipei City", "Taichung City", "Tainan City", "Kaohsiung City", "Keelung City", "Taoyuan City", "Hsinchu City", "Hsinchu County", "Miaoli County", "Changhua County", "Nantou County", "Yunlin County", "Chiayi City", "Chiayi County", "Pingtung County", "Yilan County", "Hualien County", "Taitung County", "Penghu County", "Kinmen County", "Matsu"];

var city_urls=[];
for(i=0;i<cities.length;i++){
  city_urls[i]="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22"+cities[i]+"%20City%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys"
};

//default city
$(document).ready(function(){
  $.getWeatherJSON(city_urls[0],function(data){
    var listTemp=$(this);
    listTemp.text(toCelsius(data.query.results.channel.item.condition.temp));
    update(0);
  });

})



$(".listTemps").each(function(index){
    var listTemp=$(this);
    $.getWeatherJSON(city_urls[index],function(data){
    console.log(data.query.results.channel.item.condition.temp);
    listTemp.text(toCelsius(data.query.results.channel.item.condition.temp));
});
});

function update (index){
  $.getWeatherJSON(city_urls[index],function(data){
    console.log(data);
    $(".temperature").text(toCelsius(data.query.results.channel.item.condition.temp));
    $(".date").text(data.query.results.channel.item.forecast[0].date);
    $(".description").text(data.query.results.channel.item.forecast[0].text);
    skycons.set("today", setIcon(data.query.results.channel.item.forecast[0].text));
    $(".forecast").each(function(index){
        var theDate=$(this);
        theDate.text(data.query.results.channel.item.forecast[index + 1].date);
    })
    $(".degree").each(function(index){
        var theDegree=$(this);
        theDegree.text(toCelsius(data.query.results.channel.item.forecast[index + 1].high) + " - " + toCelsius(data.query.results.channel.item.forecast[index + 1].low));
    })
    skycons.set("day1", setIcon(data.query.results.channel.item.forecast[1].text));
    skycons.set("day2", setIcon(data.query.results.channel.item.forecast[2].text));
    skycons.set("day3", setIcon(data.query.results.channel.item.forecast[3].text));
  })
};

$('#dropdown li').on('click', function(){
    // alert($(this).text());
    update($(this).find("a").attr("tabindex")-1);
    $("#toggleInfo").html($(this).find("a").html());
});

function toCelsius(fahrenheit) {
    var c = ((5 / 9) * (fahrenheit - 32)).toFixed(1)
    return Math.round(c);
}

function setIcon(description){
  if(description=="Sunny"){
     return "clear-day";
     }else if(description=="Mostly Sunny"){
       return "clear-day";
     }else if(description=="Partly Cloudy"){
       return "partly-cloudy-day";
     }else if(description=="Mostly Cloudy"){
       return "cloudy";
     }else if(description=="Cloudy"){
       return "cloudy";
     }else if(description=="Windy"){
       return "wind";
     }else if(description=="Breezy"){
       return "wind";
     }else if(description=="Fog"){
       return "fog";
     }else{
       return "rain";
     }
}
